# Generated by Django 5.2 on 2025-04-23 08:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0006_alter_order_total_price'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Pickup',
        ),
    ]
