# Generated by Django 5.2 on 2025-04-23 12:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0008_pickup'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='paid',
        ),
        migrations.AddField(
            model_name='order',
            name='method',
            field=models.CharField(choices=[('delivery', 'Delivery'), ('pickup', 'Pickup')], default=1, max_length=20),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('delivered', 'Delivered'), ('processing', 'Processing'), ('cancelled', 'Cancelled')], default=1, max_length=25),
            preserve_default=False,
        ),
    ]
