# Generated by Django 5.2 on 2025-04-24 09:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_remove_user_password_user_password_hash_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Shop',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=255)),
                ('address', models.CharField(blank=True, max_length=255)),
                ('contact', models.CharField(max_length=255)),
                ('email', models.EmailField(blank=True, max_length=254)),
                ('currency', models.CharField(blank=True, max_length=255)),
            ],
        ),
    ]
