# Generated by Django 5.2 on 2025-04-24 10:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_shop_logo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='shop',
            name='currency',
            field=models.CharField(choices=[('UGX', 'UGX'), ('USD', 'USD'), ('EUR', 'EUR'), ('GBP', 'GBP'), ('JPY', 'JPY'), ('AUD', 'AUD'), ('CAD', 'CAD')], default='UGX', max_length=20),
        ),
    ]
